import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Header } from './components/Header/Header'

const fontMontserrat = Montserrat({ 
  weight: ['700', '600', '400', '300'],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fontMontserrat.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
